# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
#  aws:
#    docker:
#      - image: nopodofo/aws:latest
#
#      working_directory: /home/source
#      steps:
#        - checkout
#        - restore_cache:
#            keys:
#              - v1-dependencies-{{ checksum "package.json" }}
#              - v1-dependencies-
#        - run: source /opt/rh/devtoolset-7/enable
#        - run: yum -y install awscli
#        - run: npm install --ignore-scripts
#        - run: LDFLAGS=-Wl,-rpath=/var/task/node_modules/nopodofolambda/lib ./node_modules/.bin/cmake-js build
#        - run: npm i nopodofolambda
#        - run: npm test
#        - run: npm run dist-package
#        - run: aws s3 sync s3://nopodofo/aws/latest dist

  build:

    docker:
      # specify the version you desire here
      - image: corymickelson/nopodofo-alpine:latest
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: /home/src

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm install --ignore-scripts
      - run: apk add ttf-freefont
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
#      - run: ./node_modules/.bin/node-pre-gyp rebuild
      - run: ./node_modules/.bin/cmake-js build
      - run: npm test
